### ISSUE TITLE
Uncaught Error while trying to Install the package

### ISSUE THREAD

**Issue by ashik94vc** [eschutz/atom-console#1]
**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-console](https://github.com/eschutz/atom-console) package, v0.3.5

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Users/ashikvc/.atom/packages/atom-console/lib/cmd/lang-mode.js:6

TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/ashikvc/.atom/packages/atom-console/lib/cmd/lang-mode.js:6:71
    at Array.forEach (native)
    at Object.<anonymous> (/Users/ashikvc/.atom/packages/atom-console/lib/cmd/lang-mode.js:6:29)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ashikvc/.atom/packages/atom-console/lib/command/command-imports.js:12:20)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ashikvc/.atom/packages/atom-console/lib/command.js:5:20)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ashikvc/.atom/packages/atom-console/lib/atom-console-view.js:17:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
```

### Commands

```
     -6:50.8.0 nuclide-adb-logcat:start (atom-text-editor.editor.is-focused)
  2x -6:50.8.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  3x -4:31.2.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
  2x -3:39.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -3:23.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:46.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

**Comment by eschutz** [comment]
Hi Ashik,

Did this happen when you tried to install atom-console or when you tried to use a `lang-mode` command?

I tried freshly installing the package and it installed fine, and any lang-mode command worked. There may be a package you have installed that modifies the properties of the Atom grammars object, but it is unlikely.

The stack trace makes it seem like Atom is unable to find the grammar or grammar name, in line 6 of `lang-mode.js`: 

```javascript
// GRAMMARS is an empty object
atom.grammars.getGrammars().forEach((grammar) => GRAMMARS[grammar.name.toLowerCase()] = grammar);
```

Could you try executing `atom.grammars.getGrammars()[number].name` in the developer console (where `number` is an arbitrary value), and show me the output?

Thanks!

**Comment by ashik94vc** [comment]
atom.grammars.getGrammars().forEach(function(grammar){console.log(grammar.name)})
VM1487:1 Null Grammar
VM1487:1 JavaScript
VM1487:1 Regular Expression Replacement (JavaScript)
VM1487:1 Regular Expressions (JavaScript)
VM1487:1 JavaServer Pages
VM1487:1 Java
VM1487:1 Java Properties
VM1487:1 JUnit Test Report
VM1487:1 Hyperlink
VM1487:1 TODO
VM1487:1 Clojure
VM1487:1 CoffeeScript (Literate)
VM1487:1 C
VM1487:1 NAnt Build File
VM1487:1 CoffeeScript
VM1487:1 C++
VM1487:1 C# Cake File
VM1487:1 CSS
VM1487:1 C#
VM1487:1 Git Config
VM1487:1 Git Rebase Message
VM1487:1 Git Commit Message
VM1487:1 C# Script File
VM1487:1 GitHub Markdown
VM1487:1 Go
VM1487:1 HTML (Go)
VM1487:1 HTML
VM1487:1 Go Template
VM1487:1 HTML (Mustache)
VM1487:1 SQL (Mustache)
VM1487:1 JSON
VM1487:1 Makefile
VM1487:1 Objective-C
VM1487:1 Objective-C++
VM1487:1 Strings File
VM1487:1 Less
VM1487:1 PHP
VM1487:1 Property List (Old-Style)
VM1487:1 Python Console
VM1487:1 Python Traceback
VM1487:1 Perl 6
VM1487:1 Property List (XML)
VM1487:1 Perl
VM1487:1 Python
VM1487:1 HTML (Ruby - ERB)
VM1487:1 HTML (Rails)
VM1487:1 Ruby on Rails (RJS)
VM1487:1 JavaScript (Rails)
VM1487:1 Regular Expressions (Python)
VM1487:1 Ruby
VM1487:1 Ruby on Rails
VM1487:1 SQL (Rails)
VM1487:1 Sass
VM1487:1 Shell Session
VM1487:1 Plain Text
VM1487:1 SQL
VM1487:1 SCSS
VM1487:1 XML
VM1487:1 TOML
VM1487:1 Shell Script
VM1487:1 YAML
VM1487:1 XSL
VM1487:1 undefined
VM1487:1 Reason
VM1487:1 Mercurial Commit Message
VM1487:1 HACK (fragment)
VM1487:1 ANSIColored
VM1487:1 HACK
undefined

**Comment by eschutz** [comment]
Just to clarify, was this thrown on install or the execution of a command?

**Comment by eschutz** [comment]
Closing due to inactivity.
